### ISSUE TITLE
Using curve Bls12-381 gives error

### ISSUE THREAD

**Issue by devindirt** [iden3/snarkjs#122]
Greetings,
When I run `snarkjs powersoftau new bls12-381 12 pot12_0000.ptau -v`

I get this error 
```
[ERROR] snarkJS: TypeError: Cannot read property 'q' of undefined
    at Object.buildBls12381 (/home/ubuntu/.nvm/versions/node/v12.21.0/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:6488:50)
    at getCurveFromName (/home/ubuntu/.nvm/versions/node/v12.21.0/lib/node_modules/snarkjs/build/cli.cjs:772:36)
    at Object.powersOfTauNew [as action] (/home/ubuntu/.nvm/versions/node/v12.21.0/lib/node_modules/snarkjs/build/cli.cjs:8461:25)
    at clProcessor (/home/ubuntu/.nvm/versions/node/v12.21.0/lib/node_modules/snarkjs/build/cli.cjs:300:31)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.21.0/lib/node_modules/snarkjs/build/cli.cjs:8119:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
```

best regards,

**Comment by devindirt** [comment]
Thanks @piotr-roslaniec

Now when moving to Contribution after using the fixed q and r error. I get this...
![image](https://user-images.githubusercontent.com/60998339/160814799-abe813ff-15e2-403b-b1cf-f6bda7b064ff.png)

Curve not Supported ? So snarkjs doesn't support bls12-381 out of the box ?

**Comment by devindirt** [comment]
i see, 

The issue seems here, params reading from wasm instead of using directly passed

![image](https://user-images.githubusercontent.com/60998339/160897172-ec0a7bc0-0231-43c4-84ba-1130ded4ad63.png)

**Comment by genievot** [comment]
> i see,
> 
> The issue seems here, params reading from wasm instead of using directly passed
> 
> ![image](https://user-images.githubusercontent.com/60998339/160897172-ec0a7bc0-0231-43c4-84ba-1130ded4ad63.png)

from global node_modules → snarkjs → node_modules → ffjavascript → build → main.cjs (like before) and find buildEngine function.
set curve.q = e(params.q); & curve.r = e(params.r);

**Comment by genievot** [comment]
> i see,
> 
> The issue seems here, params reading from wasm instead of using directly passed
> 
> ![image](https://user-images.githubusercontent.com/60998339/160897172-ec0a7bc0-0231-43c4-84ba-1130ded4ad63.png)

from global node_modules -> snarkjs -> node_modules -> ffjavascript -> build -> main.cjs (like before) and find `buildEngine` function.
set `curve.q = e(params.q);` & `curve.r = e(params.r);` in the function definition.

**Comment by phated** [comment]
This should be fixed by https://github.com/iden3/ffjavascript/pull/37 - the version of ffjavascript with that fix should be available in the latest release. Cheers 🍻

**Comment by VitalJeevanjot** [comment]
Thank you @phated. Cheers 🍻
