### ISSUE TITLE
[BUG] WebAssembly memory error on BLS12-381 new ceremony 

### ISSUE THREAD

**Issue by VictorColomb** [iden3/snarkjs#181]
## Bug description

From power 19 onwards, the `powersoftau new` command fails when using the BLS12-381 curve.

Indeed, the command `snarkjs ptn bls12-381 18 pot18_0000.ptau` succeeds in intializing a powers of tau ceremony.

But `snarkjs ptn bls12-381 19 pot19_0000.ptau` fails, producing the following error:

```text
[ERROR] snarkJS: RangeError: WebAssembly.Memory.grow(): Maximum memory size exceeded
    at Blake2b._realloc (/usr/local/lib/node_modules/snarkjs/node_modules/blake2b-wasm/index.js:75:15)
    at Blake2b.update (/usr/local/lib/node_modules/snarkjs/node_modules/blake2b-wasm/index.js:83:55)
    at hashBlock (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1116:20)
    at calculateFirstChallengeHash (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1098:5)
    at newAccumulator (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1219:32)
    at async Object.powersOfTauNew [as action] (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:8513:12)
    at async clProcessor (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:305:27)
```

## Complete log

```text
user@machine:~$ snarkjs ptn bls12-381 19 pot19_0000.ptau -v
[DEBUG] snarkJS: tauG1: 100000
[DEBUG] snarkJS: tauG1: 200000
[DEBUG] snarkJS: tauG1: 300000
[DEBUG] snarkJS: tauG1: 400000
[DEBUG] snarkJS: tauG1: 500000
[DEBUG] snarkJS: tauG1: 600000
[DEBUG] snarkJS: tauG1: 700000
[DEBUG] snarkJS: tauG1: 800000
[DEBUG] snarkJS: tauG1: 900000
[DEBUG] snarkJS: tauG1: 1000000
[DEBUG] snarkJS: tauG2: 100000
[DEBUG] snarkJS: tauG2: 200000
[DEBUG] snarkJS: tauG2: 300000
[DEBUG] snarkJS: tauG2: 400000
[DEBUG] snarkJS: tauG2: 500000
[DEBUG] snarkJS: alphaTauG1: 100000
[DEBUG] snarkJS: alphaTauG1: 200000
[DEBUG] snarkJS: alphaTauG1: 300000
[DEBUG] snarkJS: alphaTauG1: 400000
[DEBUG] snarkJS: alphaTauG1: 500000
[DEBUG] snarkJS: betaTauG1: 100000
[DEBUG] snarkJS: betaTauG1: 200000
[DEBUG] snarkJS: betaTauG1: 300000
[DEBUG] snarkJS: betaTauG1: 400000
[DEBUG] snarkJS: betaTauG1: 500000
[DEBUG] snarkJS: Calculating First Challenge Hash
[DEBUG] snarkJS: Calculate Initial Hash: tauG1
[DEBUG] snarkJS: Initial hash: 0
[DEBUG] snarkJS: Initial hash: 500000
[DEBUG] snarkJS: Calculate Initial Hash: tauG2
[ERROR] snarkJS: RangeError: WebAssembly.Memory.grow(): Maximum memory size exceeded
    at Blake2b._realloc (/usr/local/lib/node_modules/snarkjs/node_modules/blake2b-wasm/index.js:75:15)
    at Blake2b.update (/usr/local/lib/node_modules/snarkjs/node_modules/blake2b-wasm/index.js:83:55)
    at hashBlock (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1116:20)
    at calculateFirstChallengeHash (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1098:5)
    at newAccumulator (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:1219:32)
    at async Object.powersOfTauNew [as action] (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:8513:12)
    at async clProcessor (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:305:27)
```

## Context

The exact same command produced the exam same result and log output using SnarkJS versions 0.4.10 and 0.4.22, and on the following operating systems :

* Windows 11 21H2, build 22000.739 (x64)
* WSL 2 5.10.102.1 on Windows 11 build 22000.739 (x64)
* Ubuntu 22.04 LTS (x64)

**Comment by phated** [comment]
I'm not 100% certain, but this seems expected for the wasm runner. WebAssembly has a maximum memory size and snarkjs can't avoid that. If you are building large circuits, you probably want to move to [rapidsnark](https://github.com/iden3/rapidsnark) native builds.

**Comment by VictorColomb** [comment]
I am using rapidsnark to build proofs already. The problem is in generating a proving key.

The weird thing is it actually works when using curve BN128 (`snarkjs ptn bn128 20 pot20_0000.ptau`), but not with BLS12-381.
