### ISSUE TITLE
Neither contribute and prove command fails on MACI circuit(`TallyVotes`) with large params(12-3-5)

### ISSUE THREAD

**Issue by gurrpi** [iden3/snarkjs#183]
## circuit

name: TallyVotes
circuit source code: https://github.com/privacy-scaling-explorations/maci/blob/04f3597d998bd6da939ada8a895612a437d1e66a/circuits/circom/tallyVotes.circom
constrains: 33 M (33265305)
`.zkey` file Download link: https://maci-devops-zkeys.s3.ap-northeast-2.amazonaws.com/TallyVotes_12-3-5_test.0.zkey (32.8 GB, generated using `powersOfTau28_hez_final_26.ptau`)
glibc: 2.11

circom: https://github.com/iden3/circom/tree/new-simplification-heuristics had been used to compile this circuit

###  `snarkjs contribute` command failure

```
$ snarkjs zkey contribute zkeys/TallyVotes_12-3-5_test.0.zkey zkeys/TallyVotes_12-3-5_test.1.zkey --name="paik" -v
[ERROR] snarkJS: Error: zkeys/TallyVotes_12-3-5_test.0.zkey: Missing section 10
    at Object.startReadUniqueSection (/home/ubuntu/.nvm/versions/node/v16.15.1/lib/node_modules/snarkjs/node_modules/@iden3/binfileutils/build/main.cjs:96:38)
    at readMPCParams (/home/ubuntu/.nvm/versions/node/v16.15.1/lib/node_modules/snarkjs/build/cli.cjs:3971:35)
    at phase2contribute (/home/ubuntu/.nvm/versions/node/v16.15.1/lib/node_modules/snarkjs/build/cli.cjs:4867:29)
    at async clProcessor (/home/ubuntu/.nvm/versions/node/v16.15.1/lib/node_modules/snarkjs/build/cli.cjs:305:27)
```

### `snarkjs prove` command failure

```
$ snarkjs groth16 prove ./zkeys/TallyVotes_12-3-5_test.0.zkey /tmp/tmp-5853-KVC2HefSn10Z/output.wtns /tmp/tmp-5853-KVC2HefSn10Z/proof.json /tmp/tmp-5853-KVC2HefSn10Z/public.json
[ERROR] snarkJS: TypeError: Cannot read properties of undefined (reading '0')
    at Object.readSection (/home/ubuntu/.nvm/versions/node/v16.15.0/lib/node_modules/snarkjs/node_modules/@iden3/binfileutils/build/main.cjs:143:67)
    at groth16Prove$1 (/home/ubuntu/.nvm/versions/node/v16.15.0/lib/node_modules/snarkjs/build/cli.cjs:5550:54)
    at async Object.groth16Prove [as action] (/home/ubuntu/.nvm/versions/node/v16.15.0/lib/node_modules/snarkjs/build/cli.cjs:8337:36)
    at async clProcessor (/home/ubuntu/.nvm/versions/node/v16.15.0/lib/node_modules/snarkjs/build/cli.cjs:304:27
```

#### Environment

OS: Ubuntu 20.04
Node.js: v16.15.1
snarkjs: `0.4.22`

**Comment by gurrpi** [comment]
@xavi-pinsach had figured out that .zkey file had been corrupted. Regenerated one works fine. So closing this issue.

#### Regeneration detail
Used x2iedn.8xlarge (32 vCPUs, 1,024 GB memory) and took 9 hours, file size is 42 G 
.zkey file link: https://maci-develop-fra.s3.eu-central-1.amazonaws.com/TallyVotes_12-3-5_test.0.zkey
