### ISSUE TITLE
"snarkJS: Error: Scalar size does not match" on addition not multiplication 

### ISSUE THREAD

**Issue by bwuzhang** [iden3/snarkjs#203]
```
pragma circom 2.0.6;

template Addition2(){
   signal input a;  
   signal input b; 
   signal output c;  

   c <== a + b;  
}

component main = Addition2();
```
The above code gives the following error with input as` {"a": 5, "b":6}`:
```
[ERROR] snarkJS: Error: Scalar size does not match
    at _multiExp (/usr/local/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:5746:19)
    at WasmCurve.multiExpAffine (/usr/local/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:5783:22)
    at groth16Prove$1 (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:5550:33)
    at async Object.groth16Prove [as action] (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:8341:36)
    at async clProcessor (/usr/local/lib/node_modules/snarkjs/build/cli.cjs:454:27)
```
If I change the line `c <== a + b` to `c <== a * b`, the error disappears and everything works fine. 

I used the `setup.sh` and `prove.sh` from #114 
`setup.sh`: 
```
mkdir -p ptau
# Power of tau
snarkjs powersoftau new bn128 12 ptau/pot12_0000.ptau
snarkjs powersoftau contribute ptau/pot12_0000.ptau ptau/pot12_0001.ptau --name="First contribution" -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs powersoftau verify ptau/pot12_0001.ptau

# Phase 2
snarkjs powersoftau prepare phase2 ptau/pot12_0001.ptau ptau/pot12_final.ptau -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs powersoftau verify ptau/pot12_final.ptau
```

`prove.sh`: 
```
circom addition2bits.circom --r1cs --wasm --sym --c
node addition2bits_js/generate_witness.js $1_js/$1.wasm input.json witness.wtns

snarkjs groth16 setup addition2bits.r1cs ptau/pot12_final.ptau addition2bits_0000.zkey
snarkjs zkey contribute addition2bits_0000.zkey addition2bits_0001.zkey --name="1st Contributor Name" -e="$(head -n 4096 /dev/urandom | openssl sha1)"
snarkjs zkey export verificationkey addition2bits_0001.zkey verification_key.json

# Prove
snarkjs groth16 prove addition2bits_0001.zkey witness.wtns proof.json public.json

# Verify
snarkjs groth16 verify verification_key.json public.json proof.json
```
Packages: 
- snarkjs: 0.4.24
- circom: 2.0.6

Any insights are greatly appreciated!

**Comment by arc0035** [comment]
I'm also getting the same error, could anybody explains why ?

**Comment by LCamel** [comment]
The HTML generated by zkREPL also gives the same error message when generating the proof.

**Comment by LCamel** [comment]
A workaround is to manually add a dummy 1 input.
```
pragma circom 2.0.8;

template Example () {
    signal input a;
    signal input b;
    signal input dummy1; // manually assign 1 here
    signal output c;
    
    c <== (a + b) * dummy1;
}

component main = Example();

/* INPUT = {
    "a": "3",
    "b": "4",
    "dummy1": 1
} */
```
I guess circom does not work with a purely "+" circuit, even it compiles successfully.
