### ISSUE TITLE
TypeError: Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by AxelHenriot** [iden3/snarkjs#25]
Hello,

I am getting the following error when I'm trying to use the snarkjs calculatewitness function : 
TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at Object.__f [as Quest] (eval at Circuit (C:\Users\AXlHT\AppData\Roaming\npm\node_modules\snarkjs\src\circuit.js:46:33), <anonymous>:16:29)
    at RTCtx.triggerComponent (C:\Users\AXlHT\AppData\Roaming\npm\node_modules\snarkjs\src\calculateWitness.js:126:41)
    at C:\Users\AXlHT\AppData\Roaming\npm\node_modules\snarkjs\src\calculateWitness.js:167:51
    at Array.map (<anonymous>)
    at RTCtx.setSignalFullName (C:\Users\AXlHT\AppData\Roaming\npm\node_modules\snarkjs\src\calculateWitness.js:166:24)
    at RTCtx.setSignal (C:\Users\AXlHT\AppData\Roaming\npm\node_modules\snarkjs\src\calculateWitness.js:104:14)
    at C:\Users\AXlHT\AppData\Roaming\npm\node_modules\snarkjs\src\calculateWitness.js:50:17
    at iterateSelector (C:\Users\AXlHT\AppData\Roaming\npm\node_modules\snarkjs\src\calculateWitness.js:31:20)
    at iterateSelector (C:\Users\AXlHT\AppData\Roaming\npm\node_modules\snarkjs\src\calculateWitness.js:35:13)
ERROR: TypeError: Cannot convert undefined to a BigInt

Here is the circuit I have been able to compile and setup : 

template Quest(n) {
    signal private input moves[n];
    signal victory;
    signal alive;
   

    var paragraphsMapping = [[1,2,3],[4,7],[4,5], [5,6],[7,8],[0],[8,9],[0],[9,10],[99],[0]];
    var paragraphsMappingLength = 11;
    var maxOutcomeArrayLength = 3;
    var currentParagraph = 0;
    var outcomeExists = 0;

    alive <-- 1;
    victory <-- 0;

    for (var i = 0; i < n ; i++) {

        outcomeExists = 0;

        if (victory == 0 && alive == 1) {

            for (var j = 0; j < maxOutcomeArrayLength ; j++)    {
             if(paragraphsMapping[currentParagraph][j] == moves[i]) {
        outcomeExists = 1;
                }
            }
        }

        if(outcomeExists == 1) {

      if (paragraphsMapping[moves[i]][0] == 0) {
        alive <-- 0;
      }

      if (paragraphsMapping[moves[i]][0] == 99) {
        victory <-- 1;
      }

      currentParagraph = moves[i];
        }

    }

    alive === 1;
    victory === 1;

}

component main = Quest(4);

**Comment by jbaylina** [comment]
Can you check it with new version. 0.3 ?
