### ISSUE TITLE
snarkjs groth16 prove failed

### ISSUE THREAD

**Issue by zjingwang** [iden3/snarkjs#309]
### circom file
`
pragma circom 2.1.4;
template Sum(n) {
    // pay and bonus are arrays with n-dimension
    signal input pay[n];
    signal input bonus[n];
    signal input all;
    var sum = 0;
    for (var i = 0; i < n; i++) {
         sum += pay[i]*52 + bonus[i]*1;
    }

    log(sum);

    all === sum*1;
}

component main{public[all]} = Sum(6);
`

### input.json
`{
  "pay": [
    "4000",
    "7500",
    "5000",
    "1500",
    "3000",
    "4500"
  ],
  "bonus": [
    "50000",
    "0",
    "400000",
    "0",
    "100000",
    "30000"
  ],
  "all": "1906000"
}
`

###  error

`
[ERROR] snarkJS: Error: Scalar size does not match
    at _multiExp (.npm-packages/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:4976:19)
    at WasmCurve.multiExpAffine (.npm-packages/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:5013:22)
    at groth16Prove$1 (.npm-packages/lib/node_modules/snarkjs/build/cli.cjs:9905:33)
    at async Object.groth16Prove [as action] (.npm-packages/lib/node_modules/snarkjs/build/cli.cjs:12798:36)
    at async clProcessor (/home/10306229@zte.intra/.npm-packages/lib/node_modules/snarkjs/build/cli.cjs:454:27)
`

and when i traced the error, i found **buffBases.byteLength** in **main.cjs** file was zero, as follows:

`
 const nPoints = Math.floor(buffBases.byteLength / sGIn);
  const sScalar = Math.floor(buffScalars.byteLength / nPoints);
  if( sScalar * nPoints != buffScalars.byteLength) {
       throw new Error("Scalar size does not match");
   }
`
thus leading into a NAN error.

please tell me what's wrong with my circom or snarkjs.

**Comment by OBrezhniev** [comment]
You don't have non-linear constraints, that's why snarkjs gives this error.
