### ISSUE TITLE
QuotaExceededError for random bytes when verifying zkey or ptau file

### ISSUE THREAD

**Issue by Scratch-net** [iden3/snarkjs#389]
SnarkJS 0.7 produces this error. Previous version didn't
BN128, Groth16, official ptau 2**18

```snarkjs powersoftau verify powersOfTau28_hez_final_18.ptau``` 

```
...
[INFO]  snarkJS: Powers Of tau file OK!
[DEBUG] snarkJS: Verifying powers in tau*G1 section
[DEBUG] snarkJS: points relations: tauG1: 0/524287
[ERROR] snarkJS: DOMException [QuotaExceededError]: The requested length exceeds 65,536 bytes
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:663:10)
    at Crypto.getRandomValues (node:internal/crypto/random:328:11)
    at Crypto.getRandomValues (node:internal/crypto/webcrypto:1000:10)
    at getRandomBytes (/home//.nvm/versions/node/v20.3.0/lib/node_modules/snarkjs/build/cli.cjs:285:27)
```

```snarkjs zkey verify circuit.r1cs powersOfTau28_hez_final_18.ptau circuit_final.zkey```
```
[ERROR] snarkJS: DOMException [QuotaExceededError]: The requested length exceeds 65,536 bytes
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:663:10)
    at Crypto.getRandomValues (node:internal/crypto/random:328:11)
    at Crypto.getRandomValues (node:internal/crypto/webcrypto:1000:10)
    at getRandomBytes (/home//.nvm/versions/node/v20.3.0/lib/node_modules/snarkjs/build/cli.cjs:285:27)
    at sectionHasSameRatio (/home//.nvm/versions/node/v20.3.0/lib/node_modules/snarkjs/build/cli.cjs:4768:29)
    at async phase2verifyFromInit (/home//.nvm/versions/node/v20.3.0/lib/node_modules/snarkjs/build/cli.cjs:4716:10)
    at async phase2verifyFromR1cs (/home//.nvm/versions/node/v20.3.0/lib/node_modules/snarkjs/build/cli.cjs:4960:12)
    at async Object.zkeyVerifyFromR1cs [as action] (/home//.nvm/versions/node/v20.3.0/lib/node_modules/snarkjs/build/cli.cjs:13442:17)
    at async clProcessor (/home//.nvm/versions/node/v20.3.0/lib/node_modules/snarkjs/build/cli.cjs:481:27)
```
It requests 260k+ random bytes which is a bit weird

**Comment by phated** [comment]
This function now prefers the Crypto APIs instead of the nodejs APIs, so maybe there is a hard limit specified by that API (or maybe nodejs has a bug).

We might need to do something to prefer node API but that causes problems with the browser.
