### ISSUE TITLE
RangeError: Too many elements passed to Promise.all

### ISSUE THREAD

**Issue by glamperd** [iden3/snarkjs#435]

**Comment by glamperd** [comment]
When running a powersoftau prepare phase2 on a large (2^28) file, the process crashes with this error:
```
[DEBUG] snarkJS: tauG1: fft 28 join  28/28  1/1 8190/8192
[DEBUG] snarkJS: tauG1: fft 28 join  28/28  1/1 8191/8192
/usr/local/lib/nodejs/node-v18.18.0-linux-x64/lib/node_modules/snarkjs/node_modules/fastfile/build/main.cjs:167
        Promise.all(ops).then( () => {
                ^

RangeError: Too many elements passed to Promise.all
    at Function.all (<anonymous>)
    at FastFile._triggerLoad (/usr/local/lib/nodejs/node-v18.18.0-linux-x64/lib/node_modules/snarkjs/node_modules/fastfile/build/main.cjs:167:17)
    at FastFile.readToBuffer (/usr/local/lib/nodejs/node-v18.18.0-linux-x64/lib/node_modules/snarkjs/node_modules/fastfile/build/main.cjs:305:14)
    at processSectionPower (/usr/local/lib/nodejs/node-v18.18.0-linux-x64/lib/node_modules/snarkjs/build/cli.cjs:2659:29)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
    at async processSection (/usr/local/lib/nodejs/node-v18.18.0-linux-x64/lib/node_modules/snarkjs/build/cli.cjs:2641:13)
    at async preparePhase2 (/usr/local/lib/nodejs/node-v18.18.0-linux-x64/lib/node_modules/snarkjs/build/cli.cjs:2619:5)
    at async Object.powersOfTauPreparePhase2 [as action] (/usr/local/lib/nodejs/node-v18.18.0-linux-x64/lib/node_modules/snarkjs/build/cli.cjs:13288:5)
    at async clProcessor (/usr/local/lib/nodejs/node-v18.18.0-linux-x64/lib/node_modules/snarkjs/build/cli.cjs:481:27)

Node.js v18.18.0

```

**Comment by glamperd** [comment]
See PR in fastfile repo, PR [#102](https://github.com/iden3/fastfile/pull/102)
