### ISSUE TITLE
Proof valiadation not working with cirtcuit that works fine with circom tester

### ISSUE THREAD

**Issue by TheBojda** [iden3/snarkjs#446]
This is my circuit:

```
pragma circom 2.0.0;

include "../node_modules/circomlib/circuits/eddsaposeidon.circom";

template VerifyTransferRequest() {
    signal input Ax;
    signal input Ay;
    signal input S;
    signal input R8x;
    signal input R8y;

    signal input M;

    component eddsa = EdDSAPoseidonVerifier();
    eddsa.enabled <== 1;
    eddsa.Ax <== Ax;
    eddsa.Ay <== Ay;
    eddsa.S <== S;
    eddsa.R8x <== R8x;
    eddsa.R8y <== R8y;
    eddsa.M <== M;
}

component main = VerifyTransferRequest();
```

And my JS code:

```javascript
import { wasm as wasm_tester } from 'circom_tester'

const eddsa = await buildEddsa()
const poseidon = await buildPoseidon()
const babyJub = await buildBabyjub();
const F = babyJub.F;

const transactionHash = poseidon([1,2,3,4]); 
const signature = eddsa.signPoseidon(prvKey, transactionHash);

const inputs = {
            Ax: F.toObject(accounts[0].pubKey[0]),
            Ay: F.toObject(accounts[0].pubKey[1]),
            R8x: F.toObject(signature.R8[0]),
            R8y: F.toObject(signature.R8[1]),
            S: signature.S,
            M: F.toObject(transactionHash)
}

const w = await verifyTransferCircuit.calculateWitness(inputs, true);
await verifyTransferCircuit.checkConstraints(w);

const { proof, publicSignals } = await snarkjs.groth16.fullProve(
            inputs,
            "./build/verify-transfer-req-test_js/verify-transfer-req-test.wasm",
            "./build/verify-transfer-req-test.zkey");

const vKey = JSON.parse(fs.readFileSync("build/verify-transfer-req-test_vkey.json").toString());
assert(await snarkjs.groth16.verify(vKey, publicSignals, proof));
```

The verifyTransferCircuit.checkConstraints method works fine, but if I generate the proof with fullProve and verify, it throws: 

```
     Error: Scalar size does not match
      at _multiExp (node_modules/ffjavascript/build/main.cjs:4971:19)
      at WasmCurve.multiExpAffine (node_modules/ffjavascript/build/main.cjs:5008:22)
      at Object.groth16Verify [as verify] (node_modules/snarkjs/build/main.cjs:1354:31)
```

**Comment by OBrezhniev** [comment]
Closing this issue, as looks like you've found that issue is related to not having public signals: #447
