### ISSUE TITLE
snarkjs.groth16.verify is not working if pubSignals is empty

### ISSUE THREAD

**Issue by TheBojda** [iden3/snarkjs#447]
This was my test circuit:

```
pragma circom 2.0.0;

include "../../node_modules/circomlib/circuits/eddsaposeidon.circom";

component main = EdDSAPoseidonVerifier();
```

it throws

```
 Error: Scalar size does not match
      at _multiExp (node_modules/ffjavascript/build/main.cjs:4972:19)
      at WasmCurve.multiExpAffine (node_modules/ffjavascript/build/main.cjs:5009:22)
      at Object.groth16Verify [as verify] (node_modules/snarkjs/build/main.cjs:1357:31)
      at async Context.<anonymous> (test/eddsa-test.ts:55:21)
``` 

If I make some signals public, it works fine:

```
pragma circom 2.0.0;

include "../../node_modules/circomlib/circuits/eddsaposeidon.circom";

component main {public [Ax,Ay]} = EdDSAPoseidonVerifier();
```

**Comment by OBrezhniev** [comment]
Some private inputs and constraints could be removed by circom compiler:
https://docs.circom.io/circom-language/circom-insight/simplification/
Probably that's the case.
