### ISSUE TITLE
Can this library work on node v10 LTS? Error: Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by vrfox** [iden3/snarkjs#69]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/snarkjs/node_modules/ffjavascript/build/main.cjs:9:38)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

Using node v: 10.21.0

**Comment by NikitaIT** [comment]
Read Readme.md
>  While any version after v12 should work fine, we recommend you install v14 or later.

Use node `--experimental-worker` flag (But remember, this solution is not stable) or uptate to next node version.

P.S. I use Node Version Manager for such cases.

**Comment by phated** [comment]
Many things in snarkjs and underlying libraries depend on node 12+ features, so that is the minimum supported version.
