### ISSUE TITLE
PLONK prove doesn't work for Getting Started circuit. Error: Polinomial does not divide

### ISSUE THREAD

**Issue by 0xys** [iden3/snarkjs#94]
I followed the instruction as in `README.md` file with `plonk`.
But, at step [24](https://github.com/iden3/snarkjs#24-create-the-proof), it fails with the following error. witness should be correct value.

Anyone knows how to resolve it?

```
[ERROR] snarkJS: Error: Polinomial does not divide
    at divPol1 (/home/username/.nvm/versions/node/v14.17.0/lib/node_modules/snarkjs/build/cli.cjs:7188:19)
    at round5 (/home/username/.nvm/versions/node/v14.17.0/lib/node_modules/snarkjs/build/cli.cjs:7131:18)
    at plonk16Prove (/home/username/.nvm/versions/node/v14.17.0/lib/node_modules/snarkjs/build/cli.cjs:6484:11)
    at async Object.plonkProve [as action] (/home/username/.nvm/versions/node/v14.17.0/lib/node_modules/snarkjs/build/cli.cjs:8825:36)
    at async clProcessor (/home/username/.nvm/versions/node/v14.17.0/lib/node_modules/snarkjs/build/cli.cjs:280:21)
```

**Comment by 0xys** [comment]
Give you the context. My `circuit.circom` is:
```
template Multiplier() {
    signal private input a;
    signal private input b;
    signal output c;
    c <== a*b;
}

component main = Multiplier();
```

and `input.json` is:
```
{"a": 3, "b": 11}

```

**Comment by 0xys** [comment]
Solved with the latest version.
